-- AI Web Agency Database Schema

-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create leads table
CREATE TABLE IF NOT EXISTS leads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    category TEXT,
    address TEXT,
    phone TEXT,
    rating DOUBLE PRECISION,
    reviews_count INT DEFAULT 0,
    reviews_summary TEXT, -- Summary generated by AI from Google Maps reviews
    has_website BOOLEAN DEFAULT FALSE,
    website_url TEXT,
    place_id TEXT UNIQUE, -- Google Place ID
    status TEXT DEFAULT 'new', -- 'new', 'generating', 'ready', 'contacted', 'archived'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create generated_sites table
CREATE TABLE IF NOT EXISTS generated_sites (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    lead_id UUID REFERENCES leads(id) ON DELETE CASCADE,
    template_name TEXT NOT NULL, -- 'service', 'restaurant', 'business'
    theme_config JSONB NOT NULL, -- e.g. { "primary": "#1e3a8a", "secondary": "#3b82f6", "fontFamily": "Inter" }
    content JSONB NOT NULL, -- e.g. { "hero": { "title": "...", "subtitle": "..." }, "about": "...", "services": [...], "testimonials": [...] }
    edit_token UUID DEFAULT gen_random_uuid(), -- Secret token for clients to live edit the page
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
